#pragma once

const DWORD DEAD_STATUS_WAIT_TICK = 1000;
const DWORD ENEMY_MOVE_ACTION_DELAY_TICK = 500;

const DWORD MAX_AMMO_NUM = 16;
const DWORD MAX_ENEMY_NUM = 8;

const DWORD SCORE_PER_ONE_KILL = 50;

const int DEFAULT_AMMO_SPEED = 10;
const int DEFAULT_PLAYER_SPEED = 8;
const int DEFAULT_ENEMY_SPEED = 5;
